/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleTest.libPackage;

public class Library {
    public static String  someLibraryMethod() {
        return "Works";
    }
}
