/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleTest.libPackage;

public static class Library {
    public String  someLibraryMethod() {
        return "Works";
    }
}
